# Format and labels used by Ansible DevTools projects
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
# Use '-' instead of '*' for unordered list to match prettier behavior
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
categories:
  - title: 'Major Changes'
    labels:
      - 'major'  # c6476b
  - title: 'Minor Changes'
    labels:
      - 'feature'  # 006b75
      - 'enhancement'  # ededed
      - 'refactoring'
  - title: 'Bugfixes'
    labels:
      - 'bug'  # fbca04
  - title: 'Deprecations'
    labels:
      - 'deprecated'  # fef2c0
exclude-labels:
  - 'skip-changelog'
  - 'bot:chronographer:skip'
replacers:
  # https://github.com/release-drafter/release-drafter/issues/569#issuecomment-645942909
  - search: '/(?:and )?@(pre-commit-ci|dependabot)(?:\[bot\])?,?/g'
    replace: ''
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
      - 'refactoring'
  patch:
    labels:
      - 'patch'
      - 'bug'
      - 'deprecated'
  default: patch
exclude-contributors:
  - 'dependabot'
  - 'pre-commit-ci'
autolabeler:
  - label: 'skip-changelog'
    files:
      - '.pre-commit-config.yaml'
    branch:
      - '/^(chore|ci|gha|test|zuul)\/.+/'
    title:
      - '/^(chore|ci|gha|test|zuul):/i'
      - '/pre-commit autoupdate/'
    body:
      - '/type: chore/i'
  - label: 'bug'
    title:
      - '/^fix/i'
    body:
      - '/type: fix/i'
  - label: 'enhancement'
    title:
      - '/^(enhance|improve)/i'
    body:
      - '/type: enhancement/i'
  - label: 'feature'
    title:
      - '/^feat/i'
    body:
      - '/type: feature/i'
  - label: 'dreprecated'
    title:
      - '/^deprecat(ed|ion)/i'
    body:
      - '/type: deprecat(ed|ion)/i'
template: |
  $CHANGES
