---
site_name: Ansible DevTools
site_url: https://ansible.readthedocs.io/projects/team-devtools/
repo_url: https://github.com/ansible/team-devtools
edit_uri: blob/main/docs/
copyright: Copyright © Red Hat, Inc.

theme:
  name: ansible
  features:
    - content.code.copy
    - content.action.edit
    - content.tooltips
    - navigation.expand
exclude_docs: |
  _abbreviations.md
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ansible/team-devtools
nav:
  - home: index.md
  - guides:
      - Code Reviews: guides/code-reviews.md
      - Manage Releases: guides/releases.md
      - Github Actions: guides/gha.md
      - Mentoring: guides/mentoring.md
      - CalVer Releases: guides/calver.md
      - Ansible:
          - Permissions: guides/ansible/permissions.md
      - Python:
          - Python Packaging: guides/python/packaging.md
          - Python Dependencies: guides/python/dependencies.md
          - PyTest: guides/python/pytest.md
          - Tox: guides/python/tox.md
          - Release: guides/python/release.md
      - VsCode:
          - Typescript: guides/vscode/use-cases.md
          - Release: guides/vscode/release.md
  - stats:
      - Molecule Plugins: stats/molecule-plugins.md
      - Repository Status: stats/repos.md
# - ansible-language-server: '!import https://github.com/ansible/ansible-language-server?branch=main&multi_docs=False'
# - projects: "*include .cache/*/mkdocs.yml"
plugins:
  - autorefs
  - material/search
  - exclude:
      glob:
        - "*/changelog-fragments.d/*"
  - material/social
  # Disabled due to https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/issues/89
  # - git-revision-date-localized:
  #     enable_creation_date: false
  #     fallback_to_build_date: true
  #     exclude:
  #       - index.md

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - docs/_abbreviations.md
      check_paths: true
  - pymdownx.superfences
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: facelessuser
      repo: pymdown-extensions
      normalize_issue_symbols: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      # reduced to keep TOC nice under Changelog page
      toc_depth: 3
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
