---
# It is not currently possible to use trusted publishing with a shared workflow
# https://github.com/pypi/warehouse/blob/main/docs/user/trusted-publishers/troubleshooting.md#reusable-workflows-on-github
# this file is for reference only now

name: release

on:
  workflow_call:
permissions:
  contents: read

jobs:
  release:
    name: release ${{ github.event.ref }}
    environment: release
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read

    env:
      FORCE_COLOR: 1
      PY_COLORS: 1
      TOX_PARALLEL_NO_SPINNER: 1

    steps:
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          python-version: "3.14"

      - name: Install tox
        run: |
          set -euo pipefail
          uv tool install --with tox-uv tox
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Check out src from Git
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0 # needed by setuptools-scm

      - name: Build dists
        run: tox -e pkg
      - name: Publish to pypi.org
        uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247 # v1.14.1
