---
# It is not currently possible to use trusted publishing with a shared workflow
# https://github.com/pypi/warehouse/blob/main/docs/user/trusted-publishers/troubleshooting.md#reusable-workflows-on-github
# this file is for reference only now

name: release

on:
  workflow_call:
jobs:
  release:
    name: release ${{ github.event.ref }}
    environment: release
    runs-on: ubuntu-24.04
    permissions:
      id-token: write

    env:
      FORCE_COLOR: 1
      PY_COLORS: 1
      TOX_PARALLEL_NO_SPINNER: 1

    steps:
      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version: "3.14"

      - name: Install tox
        run: python3 -m pip install --user "tox>=4.0.0"

      - name: Check out src from Git
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0 # needed by setuptools-scm

      - name: Build dists
        run: python3 -m tox -e pkg
      - name: Publish to pypi.org
        uses: pypa/gh-action-pypi-publish@release/v1
